In [1]:
import numpy as np
import matplotlib as plt
import seaborn as sns
import random

In [2]:
def maping(x):
    return x*5 + 9

In [3]:
X = []
Y = []

In [4]:
for _ in range(100):
    x = np.random.randn(2,)
    y = sum(list(map(maping, x)))
    X.append(x)
    Y.append(y)

In [5]:
X = np.array(X)
Y = np.array(Y)

In [6]:
X.shape

(100, 2)

In [21]:
class Perceptron:

    def __init__(self, x, weight,  bias):
        self.x = x
        self.bias = bias
        self.weight = weight

    
    def get_output(self):
        val = self.x * self.weight + self.bias
        return val



In [22]:
class Layer:

    def __init__(self, input, y, activation):
        self.input = input
        self.y = y
        self.activation = activation
        self.weights = np.random.random(len(self.input))
        self.bias = np.random.random()
    
    def output(self):

        y_cal = []
        
        for tensor in self.input:
            sum = 0
            for idx, val in enumerate(tensor):
                p = Perceptron(x=val, weight=self.weights[idx], bias=self.bias)
                sum+=p.get_output()
            y_cal.append(sum)
        
        self.y_est = y_cal

        return self.y_est

    def cal_loss(self):
        loss = list(map(lambda x: (x[0]-x[1])**2, zip(self.y_est, self.y)))
        
        self.cur_loss = loss

        return sum(loss)/len(loss)


    def propagation(self, step=0.5):

        for val in self.input:
            
            loss = sum(list(map(lambda x: (x[0]-x[1]), zip(self.y_est, self.y))))
        
            changes = []           
            
            for idx in range(len(self.y)):
                derv = (2*loss/len(self.y_est))*val[idx]
                
                if derv>0:
                    changes.append(self.weights[idx]-(step))
                else:
                    changes.append(self.weights[idx]+(step))
            

            self.weights=changes

            self.output()
            self.cal_loss()        


            
            

        

In [23]:
l1 = Layer(input=X, y=Y,activation=lambda x: x)

In [24]:
l1.output()

[array([29.84255893, 34.94584907]),
 array([22.47059648, 28.77065657]),
 array([29.03618689, 44.8374386 ]),
 array([33.23995035, 28.25234893]),
 array([31.08758299, 33.68683873]),
 array([32.32484426, 25.98304686]),
 array([35.17505853, 28.96753015]),
 array([43.22052916, 25.77696891]),
 array([34.47759733, 20.43932279]),
 array([34.71750609, 34.99195013]),
 array([22.4425264 , 25.53822002]),
 array([35.54363823, 32.23811405]),
 array([20.59185565, 32.74007199]),
 array([24.38172166, 28.27813325]),
 array([34.89670019, 20.64036836]),
 array([35.17226506, 25.3483057 ]),
 array([41.83108649, 42.86756898]),
 array([35.1830061 , 32.74657493]),
 array([30.48888288, 32.1389411 ]),
 array([38.9537821, 39.3554329]),
 array([17.41775418, 28.89634955]),
 array([35.97398277, 41.53471385]),
 array([34.15933855, 30.36591865]),
 array([41.98037158, 33.07278598]),
 array([27.32809992, 37.34725007]),
 array([19.55473479, 30.51750928]),
 array([30.31840615, 33.9541832 ]),
 array([30.33571812, 21.974815

In [25]:
l1.cal_loss()

array([761725.42795124, 761749.43895011])

In [26]:
l1.weights

array([0.91012959, 0.59226224, 0.74928778, 0.83899609, 0.05520719,
       0.9133319 , 0.55845509, 0.10028459, 0.24890669, 0.47647284,
       0.81039613, 0.7908475 , 0.12353587, 0.79143478, 0.77687775,
       0.49186068, 0.73938988, 0.31124588, 0.50431016, 0.94692539,
       0.61768124, 0.56474745, 0.69367905, 0.52749667, 0.61242885,
       0.37968772, 0.47304373, 0.87664926, 0.8576567 , 0.00512053,
       0.46961651, 0.34999319, 0.26059769, 0.07496218, 0.4216445 ,
       0.02208588, 0.89109474, 0.58723768, 0.9553459 , 0.78400555,
       0.38502478, 0.00213854, 0.91446898, 0.11046031, 0.05981254,
       0.36515945, 0.11661766, 0.38804727, 0.56859358, 0.71501368,
       0.16763468, 0.21009597, 0.56590158, 0.48359679, 0.06031138,
       0.11121219, 0.82764017, 0.58201447, 0.52151119, 0.7907643 ,
       0.05737247, 0.96630006, 0.07419539, 0.68680323, 0.43774594,
       0.0598026 , 0.45965936, 0.99613964, 0.64495932, 0.85329139,
       0.54988146, 0.59743013, 0.06395496, 0.76396124, 0.69912

In [27]:
l1.propagation()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
l1.cal_loss()

92380986.11569908

In [ ]:
l1.cal_loss()

630394001.6952511

In [ ]:
min = 0

for _ in range(100):

    l1.propagation()

    loss = l1.cal_loss()

    if min<loss:
        min = loss

In [ ]:
min

1073279300.1111346

In [ ]:
import optuna

def objective(trial):

    step = trial.suggest_float("step", 0.1, 1, step=0.05)
    l1.propagation(step=step)
    loss = l1.cal_loss()

    return loss

In [ ]:
tuner = optuna.create_study(direction="minimize")
tuner.optimize(objective, n_trials=50)

[I 2023-02-21 23:09:28,819] A new study created in memory with name: no-name-0b9df0b9-e3f5-412a-b9d8-19b809158d46
[I 2023-02-21 23:09:29,508] Trial 0 finished with value: 390902303.87756324 and parameters: {'step': 0.85}. Best is trial 0 with value: 390902303.87756324.
[I 2023-02-21 23:09:30,205] Trial 1 finished with value: 1611584.1175215137 and parameters: {'step': 0.45000000000000007}. Best is trial 1 with value: 1611584.1175215137.
[I 2023-02-21 23:09:30,890] Trial 2 finished with value: 26046988.91219394 and parameters: {'step': 0.75}. Best is trial 1 with value: 1611584.1175215137.
[I 2023-02-21 23:09:31,574] Trial 3 finished with value: 7576981.207246948 and parameters: {'step': 0.15000000000000002}. Best is trial 1 with value: 1611584.1175215137.
[I 2023-02-21 23:09:32,265] Trial 4 finished with value: 15287016.730882114 and parameters: {'step': 0.85}. Best is trial 1 with value: 1611584.1175215137.
[I 2023-02-21 23:09:32,951] Trial 5 finished with value: 39307862.88485852 and

In [ ]:
Y

[125240,
 133500,
 129895,
 127875,
 142695,
 136525,
 127665,
 123250,
 133905,
 122060,
 126120,
 133695,
 110430,
 135155,
 113275,
 120765,
 121165,
 121400,
 123540,
 124010,
 126645,
 131780,
 138985,
 131990,
 140235,
 122460,
 128535,
 131940,
 114565,
 126205,
 131450,
 128650,
 118015,
 131580,
 125565,
 139580,
 131870,
 121490,
 118830,
 131050,
 126810,
 111705,
 132955,
 125880,
 114820,
 119090,
 126510,
 113440,
 135910,
 123155,
 140720,
 115115,
 129670,
 126970,
 131990,
 125120,
 115540,
 119095,
 126640,
 124995,
 121260,
 107900,
 132590,
 118025,
 123860,
 125510,
 123765,
 132690,
 118635,
 132965,
 133575,
 130035,
 121235,
 126965,
 118060,
 116865,
 117995,
 119815,
 136915,
 112260,
 127940,
 128915,
 124565,
 122525,
 122675,
 127740,
 117130,
 136805,
 120660,
 117525,
 134455,
 122045,
 132250,
 122360,
 137515,
 119425,
 134305,
 133675,
 128895,
 116445]

In [ ]:
(1611584**(1/2))/120000

0.01057901486696921

In [ ]:
X = np.random.randint(10,100,size=(1000,10))

array([28, 77, 75, 25, 88, 27, 36, 97, 93, 33])

In [ ]:
params = np.random.rand(10)
params = params.round(2)

In [ ]:
Y = X.dot(params)

In [ ]:
sum = 0 

for i in range(len(X[0])):
    sum += X[0][i]*params[i]
sum.round(8)==Y[0]

True

In [ ]:
print(Y[0])
print(sum)

308.53999999999996
<built-in function sum>


In [ ]:
def get_weights():
    W1 = np.random.rand(10,10).round(2)
    b1 = np.random.rand()
    W2 = np.random.rand(10,1)
    b2 = np.random.rand()
    return W1, b1, W2, b2

def forward_propagation(W1, b1, W2, b2, X):
    O1 = X.dot(W1.T)+b1
    O2 = O1.dot(W2) + b2
    return O2

In [ ]:
W1, b1, W2, b2 = get_weights()

In [ ]:
Y_pred = forward_propagation(W1,b1,W2,b2, X)

In [ ]:
def get_loss(W1, b1, W2, b2):
    Y_pred = forward_propagation(W1,b1,W2,b2,X)
    return (abs(Y_pred-Y).sum()/1000)

In [ ]:
Y =np.reshape(Y,(1000,1))

In [ ]:
def back_propagation(W1, b1, W2, b2, X, alpha):
    Y_pred = forward_propagation(W1,b1,W2,b2,X)
    loss = (Y_pred-Y)/1000
    cur_loss = get_loss(W1,b1,W2,b2)
    O1 = X.dot(W1.T)+b1
    O2 = O1.dot(W2) + b2
    dW2 = (2/1000)*(O1.T.dot(loss))
    dW1 = (2/1000)*np.dot(W2,loss.T).dot(X)

    db2 = loss.sum()/1000
    db1 = ((2/1000)*W2.dot(loss.T)).sum()/1000
    
    # print(dW2,dW1)

    W1 = W1 - alpha*(dW1.T)
    W2 = W2 - alpha*dW2
    b1 = b1 - alpha*db1
    b2 = b2 - alpha*db2

    return W1, W2, b1, b2
        



In [ ]:
cur_loss = get_loss(W1,b1,W2,b2)
print(cur_loss)

778897.2249909608


In [ ]:
cur_loss = get_loss(W1,b1,W2,b2)
losses = dict({'Loss':[],'Iteration':[]})
for i in range(1000):
    n_W1 = W1 + 0.05*np.random.randn(10,10)
    n_b1 = b1 + 0.05*np.random.randn()
    n_W2 = W2 + 0.05*np.random.randn(10,1)
    n_b2 = b2 + 0.05*np.random.randn()

    new_loss = get_loss(n_W1, n_b1, n_W2, n_b2)

    if new_loss<cur_loss:
        W1 = n_W1
        W2 = n_W2
        b1 = n_b1
        b2 = n_b2
        print(f'New low loss found \n Iteration: {i}, Loss: {new_loss}')
        cur_loss = new_loss
        losses['Loss'].append(cur_loss)
        losses['Iteration'].append(i)
    



New low loss found 
 Iteration: 0, Loss: 675525.7357413027
New low loss found 
 Iteration: 1, Loss: 665627.6385585408
New low loss found 
 Iteration: 2, Loss: 654744.5481205417
New low loss found 
 Iteration: 3, Loss: 689651.2029015257
New low loss found 
 Iteration: 4, Loss: 686377.9301065665
New low loss found 
 Iteration: 5, Loss: 709002.2893385437
New low loss found 
 Iteration: 6, Loss: 649462.7203259568
New low loss found 
 Iteration: 7, Loss: 612342.5080420817
New low loss found 
 Iteration: 8, Loss: 577625.1217297161
New low loss found 
 Iteration: 9, Loss: 571908.2236827547
New low loss found 
 Iteration: 10, Loss: 586816.3762635065
New low loss found 
 Iteration: 11, Loss: 631205.9274787662
New low loss found 
 Iteration: 12, Loss: 604285.3606476516
New low loss found 
 Iteration: 13, Loss: 572768.0018225296
New low loss found 
 Iteration: 14, Loss: 644828.9294193482
New low loss found 
 Iteration: 15, Loss: 724515.8027564081
New low loss found 
 Iteration: 16, Loss: 690304.8

In [49]:
class Dense_layer:

    def __init__(self, input):
        self.input = input
        self.weights = np.random.randn(1,input.shape[1])
        self.bias = np.random.randn()

    def forward_propagation(self, input):
        return np.dot(self.weights, input.T) + self.bias

    def backward_propagation(self, dvalues):
        self.dweights = dvalues.T.dot(self.input)
        self.dinputs = dvalues.dot(self.weights)
    
    def update(self):
        self.weights += (self.dweights*(-0.001))
        # return dvalues.T.dot(self.input)

In [50]:
class MeanSquaredLoss:

    def __init__(self, input):
        self.input = input
    
    def forward_propagation(self,input, y_true):
        return np.sqrt(((input-y_true)**2).sum()/len(y_true))

    def backward_propagation(self,input, y_true):
        self.dinputs = -2*(y_true-input)/len(y_true)

In [51]:
layer = Dense_layer(X)


In [52]:
layer1_out = layer.forward_propagation(X)

In [53]:
layer2 = Dense_layer(layer1_out.T)

In [54]:
layer2_out = layer2.forward_propagation(layer1_out.T)

In [55]:
loss = MeanSquaredLoss(layer2_out)

In [56]:
loss.forward_propagation(layer2_out,Y)

22.12458689251063

In [57]:
loss.backward_propagation(layer2_out,Y)

In [58]:
loss.dinputs.shape

(1, 100)

In [124]:
last_loss = 1000

In [79]:
for _ in range(200):
    curloss = loss.forward_propagation(layer2_out,Y)
    print(f"Cur Loss: {curloss}")
    # if loss>last_loss:
    #     break
    # else:
    #     last_loss = loss
    layer2.backward_propagation(loss.dinputs.T)
    layer.backward_propagation(layer2.dinputs)
    layer2.update()
    layer.update()
    
    layer1_out = layer.forward_propagation(X)
    layer2_out = layer2.forward_propagation(layer1_out.T)
    
    loss.backward_propagation(layer2_out,Y)
    

Cur Loss: 0.21846543131470564
Cur Loss: 0.21793523913111218
Cur Loss: 0.217406333533677
Cur Loss: 0.2168787114009826
Cur Loss: 0.2163523696191787
Cur Loss: 0.21582730508196743
Cur Loss: 0.21530351469058567
Cur Loss: 0.21478099535377912
Cur Loss: 0.2142597439877975
Cur Loss: 0.21373975751636407
Cur Loss: 0.21322103287066368
Cur Loss: 0.21270356698932263
Cur Loss: 0.21218735681839362
Cur Loss: 0.2116723993113334
Cur Loss: 0.2111586914289873
Cur Loss: 0.21064623013956982
Cur Loss: 0.21013501241865074
Cur Loss: 0.20962503524913192
Cur Loss: 0.20911629562123324
Cur Loss: 0.20860879053247317
Cur Loss: 0.20810251698765136
Cur Loss: 0.20759747199883194
Cur Loss: 0.20709365258532725
Cur Loss: 0.20659105577367357
Cur Loss: 0.20608967859762167
Cur Loss: 0.20558951809811452
Cur Loss: 0.2050905713232733
Cur Loss: 0.20459283532837508
Cur Loss: 0.20409630717583996
Cur Loss: 0.20360098393521414
Cur Loss: 0.20310686268314745
Cur Loss: 0.20261394050338122
Cur Loss: 0.20212221448672826
Cur Loss: 0.201631

In [132]:
t_weights = np.random.randn(1,2)
t_weights_2 = np.random.rand()


In [139]:
def cal_out(w1,w2):
    o1 = X.dot(w1.T)
    o2 = o1.dot(w2)
    print(o2.shape)
    loss = mean_squared_error(Y.T, o2)

    return loss

In [138]:
Y.shape

(1, 100)

In [140]:

for _ in range(50):
    cur_loss = cal_out(t_weights, t_weights_2)
    print(cur_loss)

(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(100, 1)
39690.44658546268
(

In [142]:
import numpy as nm

a = int(input("What is the first number?"))
b = int(input("What is the second number?"))

np.expm1(a)

19.085536923187668